"""
write_questions.py
-------------------
Writes comprehensive, unique, topic-specific questions directly into the
cyberquest.db for all topics × age-groups × difficulties.

Run: .venv\\Scripts\\python write_questions.py
"""

from __future__ import annotations
import sys
import os
sys.path.insert(0, os.path.dirname(__file__))

from db.database import get_db, init_db
from db.models import Question, Module

init_db()

# ─── Question bank ────────────────────────────────────────────────────────────
# Structure: topic → difficulty → list of question dicts (body, a, b, c, d, correct, explanation, hint, points)

QUESTIONS: dict[str, dict[str, list[dict]]] = {

    # ══════════════════════════════════════════════════════
    # PASSWORD SAFETY
    # ══════════════════════════════════════════════════════
    "password_safety": {
        "beginner": [
            {"body": "What makes a password strong?",
             "a": "Your pet's name", "b": "Your birthday like '2010'",
             "c": "A mix of letters, numbers, and symbols like 'Sun$42!'",
             "d": "The word 'password'",
             "correct": "c", "points": 10,
             "explanation": "A strong password mixes uppercase, lowercase, numbers, and symbols. It should not be easy to guess!",
             "hint": "Think about what would be hardest for a stranger to guess."},
            {"body": "You forgot your password. What should you do?",
             "a": "Use 'abc123' because it's easy to remember",
             "b": "Use the 'Forgot Password' option on the website",
             "c": "Ask a classmate to reset it for you",
             "d": "Leave the account forever",
             "correct": "b", "points": 10,
             "explanation": "The official 'Forgot Password' link sends a reset email to you — that's the safe way!",
             "hint": "Websites have a built-in safe option for this."},
            {"body": "Which of these is the WORST password to use?",
             "a": "T!g3r#Blue99", "b": "password123",
             "c": "Xm$8kLp!2", "d": "R4!nbow@Sky",
             "correct": "b", "points": 10,
             "explanation": "'password123' is the most commonly guessed password. Hackers try it first!",
             "hint": "Which one looks like something millions of people would use?"},
            {"body": "How many different passwords should you use for different accounts?",
             "a": "Just one — it's easier to remember",
             "b": "Two — one for school, one for fun",
             "c": "A unique one for each important account",
             "d": "It doesn't matter",
             "correct": "c", "points": 10,
             "explanation": "If a hacker gets one password and you reuse it, all your accounts are at risk. Use different passwords!",
             "hint": "Think about what happens if someone gets your one password."},
            {"body": "Where is the safest place to store your passwords?",
             "a": "In a sticky note on your monitor",
             "b": "In a text file called 'passwords.txt' on your desktop",
             "c": "In a trusted password manager app",
             "d": "In a text message to yourself",
             "correct": "c", "points": 10,
             "explanation": "Password manager apps encrypt and protect your passwords. Sticky notes and plain files can be seen by anyone!",
             "hint": "Think about which option is locked and hidden."},
            {"body": "A friend asks for your password to help you log in. What do you do?",
             "a": "Tell them — they're your friend",
             "b": "Write it down and give them the paper",
             "c": "Never share your password with anyone, not even friends",
             "d": "Share only if they promise not to tell anyone else",
             "correct": "c", "points": 10,
             "explanation": "Passwords are private. Even trusted friends might accidentally share it or get hacked themselves.",
             "hint": "Passwords are like a toothbrush — never share!"},
            {"body": "How long should a good password be?",
             "a": "4 characters — short and easy",
             "b": "6 characters — medium length",
             "c": "At least 12 characters",
             "d": "Any length is fine",
             "correct": "c", "points": 10,
             "explanation": "Longer passwords are much harder to crack. Aim for at least 12 characters.",
             "hint": "Longer is always better for security."},
        ],
        "intermediate": [
            {"body": "What is two-factor authentication (2FA)?",
             "a": "Using two different passwords",
             "b": "A second verification step like a code sent to your phone",
             "c": "Logging in twice",
             "d": "Having two accounts",
             "correct": "b", "points": 15,
             "explanation": "2FA adds an extra layer of security. Even if someone steals your password, they still need the second code.",
             "hint": "It's an extra step after entering your password."},
            {"body": "You receive an email asking you to 'verify your account' by entering your password. What do you do?",
             "a": "Enter your password — it looks official",
             "b": "Ignore it completely",
             "c": "Go directly to the website yourself without clicking the link",
             "d": "Reply with your username only",
             "correct": "c", "points": 15,
             "explanation": "Legitimate services never ask for your password via email. Always navigate directly to the site.",
             "hint": "Real companies won't ask for your password in an email."},
            {"body": "What is a 'passphrase' and why is it useful?",
             "a": "A very short password",
             "b": "A string of random words like 'BlueMountainRocketFish7!'",
             "c": "A password hint stored in the cloud",
             "d": "Your email address",
             "correct": "b", "points": 15,
             "explanation": "A passphrase of random words is both long and memorable — much stronger than a short random password.",
             "hint": "It's like a sentence that becomes your password."},
            {"body": "Your school account password has expired. What should you do?",
             "a": "Keep using the old password — it might still work",
             "b": "Use your name as the new password",
             "c": "Create a new strong password different from your old one",
             "d": "Use the same password as your email",
             "correct": "c", "points": 15,
             "explanation": "When passwords expire, create a fresh, unique one. Reusing old passwords defeats the purpose of the expiry.",
             "hint": "Fresh and unique is the goal."},
            {"body": "What does a password manager do?",
             "a": "Tells your friends your passwords",
             "b": "Posts your passwords online for backup",
             "c": "Generates and securely stores complex passwords for you",
             "d": "Makes your passwords shorter for ease",
             "correct": "c", "points": 15,
             "explanation": "A password manager creates strong, unique passwords and stores them encrypted so you only need to remember one master password.",
             "hint": "It does the hard work of remembering for you."},
        ],
        "advanced": [
            {"body": "A website stores your password in 'plaintext'. Why is this dangerous?",
             "a": "It uses more storage space",
             "b": "If the site is hacked, your password is immediately readable",
             "c": "Plaintext loads slower",
             "d": "It can cause the website to crash",
             "correct": "b", "points": 20,
             "explanation": "Proper sites hash passwords. Plaintext storage means a hacker who breaches the site instantly gets your password.",
             "hint": "Think about what 'plaintext' means — no encryption."},
            {"body": "What is a 'dictionary attack' in the context of password cracking?",
             "a": "Looking up your password in a book",
             "b": "Trying thousands of common words and phrases as passwords",
             "c": "Attacking websites that use foreign languages",
             "d": "Sending fake definitions to confuse users",
             "correct": "b", "points": 20,
             "explanation": "Dictionary attacks automatically try words from lists of common passwords. That's why dictionary words make bad passwords.",
             "hint": "Think about what a 'dictionary' contains."},
            {"body": "Why should you check if your email was in a known data breach?",
             "a": "To see who hacked you for fun",
             "b": "Because breached passwords may be used to attack your other accounts",
             "c": "It doesn't matter unless your bank account is involved",
             "d": "To report the issue to your classmates",
             "correct": "b", "points": 20,
             "explanation": "Sites like HaveIBeenPwned.com let you check. If your password was leaked, change it everywhere you used it.",
             "hint": "Leaked passwords end up on hacker lists."},
            {"body": "Which hashing algorithm is currently considered most secure for storing passwords?",
             "a": "MD5", "b": "SHA-1",
             "c": "bcrypt / Argon2", "d": "Base64 encoding",
             "correct": "c", "points": 20,
             "explanation": "bcrypt and Argon2 are designed to be slow and resistant to brute-force attacks. MD5 and SHA-1 are outdated for passwords.",
             "hint": "Think slow and salted hashing."},
            {"body": "What does 'salting' a password mean in security?",
             "a": "Adding seasoning to make it taste better",
             "b": "Adding a random value before hashing to make identical passwords hash differently",
             "c": "Encrypting the password twice",
             "d": "Shortening the password for storage",
             "correct": "b", "points": 20,
             "explanation": "A salt is a random string added to a password before hashing. It prevents attackers from using precomputed hash tables (rainbow tables).",
             "hint": "It makes two identical passwords look different in storage."},
        ],
    },

    # ══════════════════════════════════════════════════════
    # PHISHING
    # ══════════════════════════════════════════════════════
    "phishing": {
        "beginner": [
            {"body": "You get an email saying 'You won a free iPhone! Click here!' What should you do?",
             "a": "Click immediately — it's probably real",
             "b": "Delete it — it's almost certainly a scam",
             "c": "Forward it to all your friends",
             "d": "Reply with your home address to claim the prize",
             "correct": "b", "points": 10,
             "explanation": "If something sounds too good to be true online, it almost always is. These are common phishing tricks.",
             "hint": "Would a stranger really give you a free phone?"},
            {"body": "What is phishing?",
             "a": "A hobby where you catch fish with a rod",
             "b": "A trick to steal your personal information using fake messages",
             "c": "A type of computer virus",
             "d": "A way to speed up the internet",
             "correct": "b", "points": 10,
             "explanation": "Phishing uses fake emails, texts, or websites to trick you into giving away passwords, card numbers, or personal data.",
             "hint": "The name comes from 'fishing' for victims."},
            {"body": "Which of these email sender addresses looks suspicious?",
             "a": "support@google.com",
             "b": "noreply@amazon.com",
             "c": "admin@g00gle-secure.ru",
             "d": "info@school.edu",
             "correct": "c", "points": 10,
             "explanation": "Scammers use lookalike domains with numbers replacing letters (g00gle) or strange country codes (.ru) to fool you.",
             "hint": "Look carefully at every letter in the domain."},
            {"body": "A message says 'Act NOW or your account will be deleted!' This is likely:",
             "a": "A real urgent warning from the service",
             "b": "A phishing attempt using urgency to panic you",
             "c": "A helpful reminder",
             "d": "An automated security test",
             "correct": "b", "points": 10,
             "explanation": "Creating panic and urgency is a classic phishing tactic to stop you from thinking clearly.",
             "hint": "Real services give you time. Scammers want you to rush."},
            {"body": "You get a text from an unknown number with a link. What do you do?",
             "a": "Click the link — it might be important",
             "b": "Do not click. Tell a trusted adult and delete the message",
             "c": "Reply asking who it is",
             "d": "Forward it to all contacts",
             "correct": "b", "points": 10,
             "explanation": "Unsolicited links from unknown sources can lead to harmful websites that steal your information or install malware.",
             "hint": "When in doubt, don't click!"},
        ],
        "intermediate": [
            {"body": "What is 'spear phishing'?",
             "a": "Phishing that uses fish-themed emails",
             "b": "A targeted phishing attack personalised to a specific individual",
             "c": "Phishing done through video calls",
             "d": "A type of password cracker",
             "correct": "b", "points": 15,
             "explanation": "Spear phishing uses personal details about you (name, school, friends) to make the fake message seem more convincing.",
             "hint": "It's more precise and personal than regular phishing."},
            {"body": "How can you verify if a suspicious link is safe before clicking?",
             "a": "Just click and see what happens",
             "b": "Hover over the link to preview the actual URL before clicking",
             "c": "Google the link text",
             "d": "Ask a friend to click it first",
             "correct": "b", "points": 15,
             "explanation": "Hovering reveals the real URL behind a hyperlink. If it doesn't match what you expect, don't click!",
             "hint": "Most computers show the real URL when you hover without clicking."},
            {"body": "What does HTTPS in a website address mean for security?",
             "a": "The site is 100% safe and trustworthy",
             "b": "The connection is encrypted, but the site could still be fake",
             "c": "The site is owned by the government",
             "d": "Nothing — it's just a prefix",
             "correct": "b", "points": 15,
             "explanation": "HTTPS encrypts data in transit, but criminals can also set up HTTPS phishing sites. Always verify the full domain.",
             "hint": "Encryption and trustworthiness are different things."},
            {"body": "A phishing email has perfect spelling and your real name. This means:",
             "a": "It is definitely legitimate",
             "b": "It's probably from your school",
             "c": "It could be a sophisticated spear phishing attempt",
             "d": "You can safely reply with your details",
             "correct": "c", "points": 15,
             "explanation": "Well-crafted phishing emails can look very professional. Always verify through official channels regardless of quality.",
             "hint": "Good spelling doesn't mean it's genuine."},
            {"body": "What should you do if you accidentally clicked a phishing link?",
             "a": "Do nothing — one click can't hurt",
             "b": "Close the page, change your passwords, and tell a trusted adult immediately",
             "c": "Click the back button and ignore it",
             "d": "Delete your email account",
             "correct": "b", "points": 15,
             "explanation": "Acting fast limits the damage. Change passwords, check for unusual account activity, and report the incident.",
             "hint": "Speed matters when security is compromised."},
        ],
        "advanced": [
            {"body": "What is 'vishing'?",
             "a": "Phishing through video games",
             "b": "Voice phishing — using phone calls to trick victims",
             "c": "A phishing attack on virtual reality platforms",
             "d": "Phishing using virus attachments",
             "correct": "b", "points": 20,
             "explanation": "Vishing scammers call pretending to be banks or tech support to extract passwords or financial details over the phone.",
             "hint": "The 'v' stands for voice."},
            {"body": "What is 'smishing'?",
             "a": "Phishing through social media messages",
             "b": "Phishing through email with smart formatting",
             "c": "Phishing through SMS text messages",
             "d": "A type of network attack",
             "correct": "c", "points": 20,
             "explanation": "Smishing uses SMS messages with malicious links or requests for personal information.",
             "hint": "The 'sm' stands for SMS."},
            {"body": "A hacker registers 'paypa1.com' to impersonate PayPal. This technique is called:",
             "a": "DNS poisoning", "b": "Typosquatting",
             "c": "Man-in-the-middle", "d": "SQL injection",
             "correct": "b", "points": 20,
             "explanation": "Typosquatting uses domains that look like popular sites with slight misspellings or character substitutions to catch inattentive users.",
             "hint": "Think about the word 'typo'."},
            {"body": "Which email header should you examine to detect a spoofed sender?",
             "a": "Subject line", "b": "The 'From' display name",
             "c": "The 'Reply-To' and 'Return-Path' fields",
             "d": "The email body",
             "correct": "c", "points": 20,
             "explanation": "Spoofed emails may show a legitimate 'From' name but the Reply-To and Return-Path headers reveal the true origin.",
             "hint": "Look beyond the display name to the actual routing headers."},
            {"body": "What is a 'watering hole' attack?",
             "a": "Hacking into water company systems",
             "b": "Infecting a website frequently visited by targets so they get hacked when they visit",
             "c": "A phishing email disguised as a water bill",
             "d": "Attacking a network from multiple sources simultaneously",
             "correct": "b", "points": 20,
             "explanation": "Like predators at a watering hole, attackers compromise sites their targets regularly visit, waiting for victims to come to them.",
             "hint": "Think about predators waiting where prey naturally gather."},
        ],
    },

    # ══════════════════════════════════════════════════════
    # PRIVACY
    # ══════════════════════════════════════════════════════
    "privacy": {
        "beginner": [
            {"body": "Which of these is safe to share publicly online?",
             "a": "Your home address", "b": "Your school name",
             "c": "Your favourite book or movie", "d": "Your phone number",
             "correct": "c", "points": 10,
             "explanation": "Sharing a favourite book or movie is harmless. Home addresses, school names, and phone numbers can put you at risk.",
             "hint": "Think about what a stranger could misuse."},
            {"body": "A stranger online asks for your full name and age. You should:",
             "a": "Tell them — it's just basic info",
             "b": "Tell them only your first name",
             "c": "Not share personal info with strangers online",
             "d": "Give them a fake address to be safe",
             "correct": "c", "points": 10,
             "explanation": "Strangers online are not always who they claim to be. Never share personal information with people you do not know in real life.",
             "hint": "Online strangers are like strangers in real life."},
            {"body": "What does 'private account' mean on a social media app?",
             "a": "Your account is hidden from the internet completely",
             "b": "Only approved followers can see your posts",
             "c": "You can only see other private accounts",
             "d": "The app stores your data privately on your device",
             "correct": "b", "points": 10,
             "explanation": "A private account means only people you approve as followers can see what you post.",
             "hint": "It controls who can view your content."},
            {"body": "You post a photo of yourself at home. What private information might it reveal?",
             "a": "Your favourite colour", "b": "Your age",
             "c": "Your home location or address through window signs or landmarks",
             "d": "Your shoe size",
             "correct": "c", "points": 10,
             "explanation": "Photos taken at home can reveal your neighbourhood, house appearance, or address through visible street signs and landmarks.",
             "hint": "Look for what's in the background of photos."},
            {"body": "Why should you read an app's privacy settings?",
             "a": "Just for fun", "b": "To find hidden games",
             "c": "To understand and control what personal data the app can access",
             "d": "It is required by law to read everything",
             "correct": "c", "points": 10,
             "explanation": "Privacy settings let you control what data apps can see and share, like your location, contacts, or camera.",
             "hint": "It tells you what the app can do with your information."},
        ],
        "intermediate": [
            {"body": "What are 'cookies' in the context of websites?",
             "a": "Sweet treats websites give you as rewards",
             "b": "Small files websites store on your device to remember your activity",
             "c": "Malware disguised as ads",
             "d": "Tools hackers use to steal data",
             "correct": "b", "points": 15,
             "explanation": "Cookies are small data files websites use to remember logins, preferences, and track browsing behaviour across sessions.",
             "hint": "They help websites 'remember' you."},
            {"body": "What is metadata in a photo?",
             "a": "The filter applied to the photo",
             "b": "Hidden data including when, where, and with what device the photo was taken",
             "c": "The photo's colour profile",
             "d": "The file name",
             "correct": "b", "points": 15,
             "explanation": "Photo metadata (EXIF data) can include GPS coordinates of where you were when you took the picture — a serious privacy risk.",
             "hint": "It's the hidden data inside the photo file itself."},
            {"body": "What does VPN stand for and what does it do?",
             "a": "Very Private Network — encrypts all emails",
             "b": "Virtual Private Network — encrypts your internet connection and hides your IP address",
             "c": "Verified Protection Node — scans for viruses",
             "d": "Visual Privacy Navigator — blocks ads",
             "correct": "b", "points": 15,
             "explanation": "A VPN creates an encrypted tunnel for your internet traffic and masks your real IP address, improving privacy.",
             "hint": "It creates a private tunnel for your internet data."},
            {"body": "Why is it risky to use the same username across many different sites?",
             "a": "It uses up more data",
             "b": "People can link your activity across sites to build a profile about you",
             "c": "Some sites block duplicate usernames",
             "d": "It slows down your internet",
             "correct": "b", "points": 15,
             "explanation": "The same username across platforms allows strangers to aggregate information about you from multiple sources.",
             "hint": "Think about connecting the dots across websites."},
            {"body": "When should you allow an app to access your location?",
             "a": "Always — apps need it to work",
             "b": "Never — location is always private",
             "c": "Only when necessary and only for apps you trust",
             "d": "Only when connected to WiFi",
             "correct": "c", "points": 15,
             "explanation": "Only grant location access to apps that genuinely need it (like maps) and choose 'only while using the app' when possible.",
             "hint": "Ask yourself: does this app really need to know where I am?"},
        ],
        "advanced": [
            {"body": "What is the GDPR and who does it protect?",
             "a": "A US cybersecurity law protecting companies",
             "b": "The EU's General Data Protection Regulation protecting citizens' personal data rights",
             "c": "A global internet speed standard",
             "d": "A Google privacy policy",
             "correct": "b", "points": 20,
             "explanation": "GDPR gives EU citizens rights over their personal data including the right to access, correct, and delete data companies hold about them.",
             "hint": "Think EU data rights regulation."},
            {"body": "What is 'differential privacy'?",
             "a": "Different privacy settings for different users",
             "b": "A mathematical technique allowing useful data analysis without revealing individual data points",
             "c": "Privacy laws that differ by country",
             "d": "A VPN protocol",
             "correct": "b", "points": 20,
             "explanation": "Differential privacy adds mathematical noise to datasets so that individual records cannot be identified while overall patterns remain meaningful.",
             "hint": "It's a mathematical approach to hiding individuals in data."},
            {"body": "What is 'data minimisation' as a privacy principle?",
             "a": "Storing data in compressed formats",
             "b": "Collecting only the minimum data necessary for a specific purpose",
             "c": "Deleting data after 30 days",
             "d": "Using small file sizes for privacy",
             "correct": "b", "points": 20,
             "explanation": "Privacy-by-design means collecting only what you truly need. Less data collected means less data that can be breached or misused.",
             "hint": "Less is more when it comes to data collection."},
            {"body": "What is a 'browser fingerprint'?",
             "a": "A physical fingerprint scanner on your browser",
             "b": "A unique identifier created from your browser's settings, plugins, and screen size to track you",
             "c": "A password stored by the browser",
             "d": "A cookie used for login",
             "correct": "b", "points": 20,
             "explanation": "Even without cookies, websites can identify you by combining unique browser characteristics to create a 'fingerprint'.",
             "hint": "It's how sites can track you even without cookies."},
            {"body": "What is the 'right to be forgotten'?",
             "a": "The right to use the internet anonymously",
             "b": "The legal right to request organisations delete your personal data",
             "c": "The right to forget your own passwords",
             "d": "A rule requiring websites to log out users automatically",
             "correct": "b", "points": 20,
             "explanation": "Under GDPR, individuals can request that organisations erase their personal data in certain circumstances.",
             "hint": "It's a legal right granted by EU data law."},
        ],
    },

    # ══════════════════════════════════════════════════════
    # SOCIAL MEDIA SAFETY
    # ══════════════════════════════════════════════════════
    "social_media": {
        "beginner": [
            {"body": "Someone you have never met asks to be your friend online. What should you do?",
             "a": "Accept — the more friends the better",
             "b": "Accept only if they have a profile picture",
             "c": "Decline — only connect with people you know in real life",
             "d": "Send them your phone number first",
             "correct": "c", "points": 10,
             "explanation": "Online strangers may not be who they claim. Only connect with people you actually know and trust in real life.",
             "hint": "Would you let a stranger into your home?"},
            {"body": "You see a mean comment about a classmate online. What should you do?",
             "a": "Join in to be popular",
             "b": "Ignore it completely",
             "c": "Report it, support the classmate, and tell a trusted adult",
             "d": "Share it so others can see",
             "correct": "c", "points": 10,
             "explanation": "Cyberbullying hurts real people. Reporting it, showing support, and involving adults is the right thing to do.",
             "hint": "Think about how you'd want to be treated."},
            {"body": "Before posting a photo online, you should ask yourself:",
             "a": "If it will get many likes",
             "b": "If it is funny enough",
             "c": "If it could embarrass you or others, or reveal private information",
             "d": "If the lighting is good",
             "correct": "c", "points": 10,
             "explanation": "Once something is posted online, it can be difficult to completely remove. Think before you post!",
             "hint": "The internet has a very long memory."},
            {"body": "What is the minimum age for most social media platforms like TikTok and Instagram?",
             "a": "10 years old", "b": "13 years old",
             "c": "16 years old", "d": "18 years old",
             "correct": "b", "points": 10,
             "explanation": "Most major social media platforms require users to be at least 13. This is to protect younger children.",
             "hint": "This age is common across most major platforms."},
            {"body": "Someone online claims to be a famous celebrity and asks you for your phone number. You should:",
             "a": "Give it — it could really be them",
             "b": "Never give your phone number to strangers, even if they seem famous",
             "c": "Give your parent's number instead",
             "d": "Ask for proof then decide",
             "correct": "b", "points": 10,
             "explanation": "Real celebrities do not randomly message fans for personal information. This is a common scam tactic.",
             "hint": "Real celebrities have better ways to contact fans."},
        ],
        "intermediate": [
            {"body": "What does it mean to 'screenshot and share' without permission?",
             "a": "Taking photos of your own screen for notes",
             "b": "Sharing someone's private message publicly without their consent — a privacy violation",
             "c": "Saving a post you like for later",
             "d": "Backing up your data",
             "correct": "b", "points": 15,
             "explanation": "Sharing someone's private messages or photos without permission violates their privacy and trust, and may be illegal.",
             "hint": "Would they want you to share that?"},
            {"body": "What is 'catfishing'?",
             "a": "Fishing for catfish in rivers",
             "b": "Creating a fake online identity to deceive others",
             "c": "Stealing cat photos for your profile",
             "d": "Hacking social media accounts",
             "correct": "b", "points": 15,
             "explanation": "Catfishing involves using a fake persona online to manipulate or deceive people, often building false relationships.",
             "hint": "Fake identity used to deceive."},
            {"body": "Your social media profile is set to 'public'. This means:",
             "a": "Only government agencies can see it",
             "b": "Anyone on the internet, including strangers, can see everything you post",
             "c": "Only your country can see it",
             "d": "Friends can see it but not their friends",
             "correct": "b", "points": 15,
             "explanation": "A public profile is visible to absolutely anyone who visits your profile, worldwide.",
             "hint": "Public means completely open to everyone."},
            {"body": "What is 'digital footprint'?",
             "a": "The size of files you download",
             "b": "The trail of data you leave behind from all your online activities",
             "c": "Your internet speed measurement",
             "d": "The number of followers you have",
             "correct": "b", "points": 15,
             "explanation": "Everything you do online — posts, searches, comments — leaves a digital footprint that can be tracked and stored.",
             "hint": "Like footprints in sand, you leave traces everywhere online."},
            {"body": "Someone sends you a distressing message late at night on social media. What should you do?",
             "a": "Reply immediately no matter how you feel",
             "b": "Take a screenshot, close the app, and speak to a trusted adult in the morning",
             "c": "Delete your account",
             "d": "Share it with all your friends",
             "correct": "b", "points": 15,
             "explanation": "Preserving evidence (screenshot), stepping away, and involving a trusted adult is the safest response to distressing messages.",
             "hint": "Evidence first, then get help from an adult."},
        ],
        "advanced": [
            {"body": "What is 'algorithmic amplification' and why is it a concern?",
             "a": "Making your posts louder online",
             "b": "Algorithms prioritising emotionally charged content which can spread misinformation rapidly",
             "c": "A sound enhancement feature on social apps",
             "d": "A coding technique for faster loading",
             "correct": "b", "points": 20,
             "explanation": "Social media algorithms reward engagement. Outrage and sensational content gets amplified, which can spread misinformation faster than corrections.",
             "hint": "Algorithms boost what gets the most reaction — not what's most accurate."},
            {"body": "What is 'doxing'?",
             "a": "Documenting online activity for research",
             "b": "Publishing someone's private personal information online without consent to harass them",
             "c": "Blocking someone from your account",
             "d": "Sending anonymous messages",
             "correct": "b", "points": 20,
             "explanation": "Doxing involves revealing private details like home addresses, phone numbers, or workplaces online as a form of harassment or intimidation.",
             "hint": "It exposes private info publicly as a weapon."},
            {"body": "What does 'end-to-end encryption' in a messaging app mean?",
             "a": "Messages are encrypted only at the sending end",
             "b": "Only the sender and recipient can read the messages — not even the app company",
             "c": "Messages are encrypted for 24 hours then deleted",
             "d": "The app encrypts ads you see",
             "correct": "b", "points": 20,
             "explanation": "E2E encryption means messages are locked at the sender's device and can only be unlocked by the recipient's device.",
             "hint": "Even the service provider can't read the messages."},
            {"body": "What is 'context collapse' on social media?",
             "a": "Your app crashing due to too many posts",
             "b": "Different audiences seeing the same post in completely different contexts, causing misunderstanding",
             "c": "A feature that hides old posts",
             "d": "When a hashtag stops trending",
             "correct": "b", "points": 20,
             "explanation": "A post meant for friends may be seen by employers, family, or strangers who interpret it completely differently. All audiences collapse into one.",
             "hint": "Different audiences, different interpretations of the same content."},
            {"body": "Under what circumstances can law enforcement access your social media messages?",
             "a": "Never — all messages are private",
             "b": "Only if you're famous",
             "c": "With a valid court order or under applicable laws depending on the platform and jurisdiction",
             "d": "Anytime they want with no restrictions",
             "correct": "c", "points": 20,
             "explanation": "Law enforcement typically needs legal authority like a warrant or court order to compel platforms to provide user data.",
             "hint": "There are legal frameworks governing this — not absolute access or absolute privacy."},
        ],
    },

    # ══════════════════════════════════════════════════════
    # CYBERBULLYING
    # ══════════════════════════════════════════════════════
    "cyberbullying": {
        "beginner": [
            {"body": "Which of these is an example of cyberbullying?",
             "a": "Sending a friend a funny cat video",
             "b": "Repeatedly sending mean or threatening messages to someone online",
             "c": "Playing an online game with a friend",
             "d": "Disagreeing with someone politely in a comment",
             "correct": "b", "points": 10,
             "explanation": "Cyberbullying is repeated harmful behaviour online — like mean messages, spreading rumours, or excluding someone on purpose.",
             "hint": "Think about whether it's meant to hurt the person."},
            {"body": "If someone is cyberbullying you, what is the FIRST thing you should do?",
             "a": "Bully them back to teach them a lesson",
             "b": "Tell all your friends to gang up on the bully",
             "c": "Block the person, save evidence, and tell a trusted adult",
             "d": "Delete your accounts",
             "correct": "c", "points": 10,
             "explanation": "Blocking stops further harassment, saving evidence helps adults understand what happened, and telling an adult gets you support.",
             "hint": "Block, save, tell."},
            {"body": "Cyberbullying can happen:",
             "a": "Only during school hours",
             "b": "Only on gaming platforms",
             "c": "Anywhere online, at any time — 24 hours a day",
             "d": "Only if you have a public account",
             "correct": "c", "points": 10,
             "explanation": "Unlike traditional bullying, cyberbullying can follow victims into their homes and happens at any hour, making it particularly difficult to escape.",
             "hint": "The internet has no school bell or bedtime."},
            {"body": "A friend shows you a mean meme about a classmate. What should you do?",
             "a": "Like and share it — it's funny",
             "b": "Ignore it — it's not your problem",
             "c": "Refuse to share it and tell your friend that sharing it is unkind",
             "d": "Show it to more people",
             "correct": "c", "points": 10,
             "explanation": "Sharing hurtful content — even if you didn't make it — makes you part of the bullying. Standing up is the right thing to do.",
             "hint": "Sharing harmful content makes you part of the problem."},
            {"body": "How might cyberbullying affect the person being bullied?",
             "a": "It makes them more popular",
             "b": "It has no real effect since it's just online",
             "c": "It can cause serious anxiety, depression, and reluctance to go to school",
             "d": "It only affects adults",
             "correct": "c", "points": 10,
             "explanation": "Online bullying causes real emotional harm. Research shows victims suffer anxiety, depression, lower self-esteem, and academic problems.",
             "hint": "Online words hurt just as much as real-world words."},
        ],
        "intermediate": [
            {"body": "What is the difference between cyberbullying and conflict?",
             "a": "There is no difference",
             "b": "Conflict involves two people disagreeing as equals; cyberbullying is repeated, intentional harm by a more powerful person",
             "c": "Cyberbullying only involves strangers, conflict is with friends",
             "d": "Conflict is worse than cyberbullying",
             "correct": "b", "points": 15,
             "explanation": "A disagreement between equals is normal conflict. Cyberbullying is a repeated, deliberate power imbalance aimed at causing harm.",
             "hint": "Think about intention, repetition, and power imbalance."},
            {"body": "What should a bystander do when they witness cyberbullying?",
             "a": "Stay out of it completely",
             "b": "Join in to not be left out",
             "c": "Support the victim privately, report the content, and tell a trusted adult",
             "d": "Share the bullying posts to show everyone",
             "correct": "c", "points": 15,
             "explanation": "Bystanders have power to help. Private support matters, reporting removes the content, and adults can intervene.",
             "hint": "Silent bystanders allow bullying to continue."},
            {"body": "Someone creates a fake account pretending to be you and posts embarrassing things. This is called:",
             "a": "Hacking", "b": "Impersonation and identity fraud",
             "c": "Phishing", "d": "Trolling",
             "correct": "b", "points": 15,
             "explanation": "Creating a fake profile in someone else's name to harm their reputation is impersonation — a serious form of cyberbullying that may be illegal.",
             "hint": "It involves pretending to be someone you're not."},
            {"body": "Why might victims of cyberbullying not report it to adults?",
             "a": "They enjoy the attention", "b": "Adults have no power to help online",
             "c": "Fear of making things worse, having devices taken away, or not being believed",
             "d": "It's against school rules to report",
             "correct": "c", "points": 15,
             "explanation": "Many victims fear retaliation, loss of device privileges, or being dismissed. Adults must create safe, non-judgmental spaces for reporting.",
             "hint": "Fear of consequences often stops victims from speaking up."},
            {"body": "How can you protect your online reputation from cyberbullying?",
             "a": "Post as much as possible to counter negative content",
             "b": "Use privacy settings, think before posting, and document incidents if they happen",
             "c": "Never use the internet",
             "d": "Only use apps that don't require an account",
             "correct": "b", "points": 15,
             "explanation": "Proactive steps like strong privacy settings and careful posting reduce risk. Documentation is essential if bullying occurs.",
             "hint": "Prevention and documentation are both key."},
        ],
        "advanced": [
            {"body": "What legal protections exist against cyberbullying in many countries?",
             "a": "None — cyberbullying is not a legal issue",
             "b": "Laws covering harassment, defamation, stalking, and in some places specific cyberbullying legislation",
             "c": "Only copyright laws apply",
             "d": "Only schools can punish cyberbullying",
             "correct": "b", "points": 20,
             "explanation": "Existing laws on harassment, stalking, and defamation often apply online. Some countries have specific cyberbullying laws for severe cases.",
             "hint": "Real-world harassment laws generally apply online too."},
            {"body": "What is 'cyber-stalking' and how does it differ from cyberbullying?",
             "a": "They are the same thing",
             "b": "Cyber-stalking is obsessive online monitoring and following of a specific person, often to cause fear",
             "c": "Cyber-stalking only happens to celebrities",
             "d": "Cyber-stalking only involves offline contact",
             "correct": "b", "points": 20,
             "explanation": "Cyber-stalking involves tracking, monitoring, and persistently contacting a victim to instil fear. It's more obsessive and targeted than general cyberbullying.",
             "hint": "Think obsessive tracking versus general harassment."},
            {"body": "How do anonymity tools affect cyberbullying behaviour?",
             "a": "Anonymity has no effect on behaviour",
             "b": "Anonymity often emboldens people to behave more aggressively than they would in person",
             "c": "Anonymous people are always kinder online",
             "d": "Anonymity protects victims, not bullies",
             "correct": "b", "points": 20,
             "explanation": "The 'online disinhibition effect' shows people say things anonymously online that they would never say to someone's face. Anonymity reduces accountability.",
             "hint": "No consequences = worse behaviour."},
            {"body": "What is the role of platforms in addressing cyberbullying?",
             "a": "Platforms have no responsibility — it's users' problem",
             "b": "Platforms must provide reporting tools, moderate content, enforce policies, and cooperate with law enforcement",
             "c": "Platforms only need to delete accounts when asked",
             "d": "Only governments can address cyberbullying",
             "correct": "b", "points": 20,
             "explanation": "Platform responsibility is a growing legal and ethical expectation. Safe design, clear policies, and responsive moderation all play essential roles.",
             "hint": "Platforms have power and responsibility to protect users."},
            {"body": "What psychological concept explains why online groups can become more extreme over time?",
             "a": "Digital empathy", "b": "Group polarisation",
             "c": "Social cohesion", "d": "Online moderation",
             "correct": "b", "points": 20,
             "explanation": "Group polarisation is the tendency for group members to adopt more extreme positions than they individually held, amplified by algorithm-driven echo chambers.",
             "hint": "Groups tend to drift toward more extreme versions of shared views."},
        ],
    },

    # ══════════════════════════════════════════════════════
    # SAFE DOWNLOADS
    # ══════════════════════════════════════════════════════
    "safe_downloads": {
        "beginner": [
            {"body": "Where is the safest place to download apps?",
             "a": "Any website offering free downloads",
             "b": "Pop-up ads that say 'Download Now!'",
             "c": "Official app stores like Google Play or Apple App Store",
             "d": "Links sent by friends in chat",
             "correct": "c", "points": 10,
             "explanation": "Official app stores review apps for safety. Random websites can offer malware disguised as free apps.",
             "hint": "Stick to the official store for your device."},
            {"body": "An app asks for permission to access your contacts and camera. It's a simple flashlight app. What should you do?",
             "a": "Accept all permissions — they must need them",
             "b": "Deny permissions that the app doesn't need to do its job",
             "c": "Uninstall your flashlight",
             "d": "Share the app with friends",
             "correct": "b", "points": 10,
             "explanation": "A flashlight app only needs the camera/flash. Requesting contacts is suspicious and unnecessary — likely harvesting your data.",
             "hint": "Does a flashlight really need your contacts?"},
            {"body": "What is malware?",
             "a": "A software update that improves security",
             "b": "Harmful software designed to damage, steal data, or take control of your device",
             "c": "A type of antivirus program",
             "d": "A website that is slow to load",
             "correct": "b", "points": 10,
             "explanation": "Malware (malicious software) includes viruses, ransomware, spyware, and more — all designed to harm your device or steal information.",
             "hint": "Mal = bad, ware = software."},
            {"body": "Before downloading a free app, what should you check?",
             "a": "How colourful the icon is",
             "b": "The app's ratings, reviews, publisher name, and permissions required",
             "c": "Whether your friends use it",
             "d": "If the file size is under 1MB",
             "correct": "b", "points": 10,
             "explanation": "Reviews, ratings, and publisher verification help identify legitimate apps. Suspicious permissions are a red flag.",
             "hint": "Look for reputation and red flags before installing."},
            {"body": "Your device says 'Update Available'. What should you do?",
             "a": "Ignore it — updates break things",
             "b": "Wait 6 months before updating",
             "c": "Install updates promptly — they often fix security vulnerabilities",
             "d": "Only update if friends say it's good",
             "correct": "c", "points": 10,
             "explanation": "Security updates patch known vulnerabilities. Delaying updates leaves your device exposed to known attacks.",
             "hint": "Updates fix security holes — install them promptly."},
        ],
        "intermediate": [
            {"body": "What is ransomware?",
             "a": "Software that improves computer performance",
             "b": "Malware that encrypts your files and demands payment for the decryption key",
             "c": "A type of antivirus",
             "d": "A program that randomly deletes old files",
             "correct": "b", "points": 15,
             "explanation": "Ransomware locks your files by encrypting them, then demands money (ransom) to restore access. Paying doesn't guarantee recovery.",
             "hint": "Think 'ransom' + software."},
            {"body": "What is a 'trojan horse' in cybersecurity?",
             "a": "A virus named after the ancient Greek myth that appears as legitimate software but hides malicious code",
             "b": "A firewall technique",
             "c": "An old Greek computer",
             "d": "A hacking tool for networks",
             "correct": "a", "points": 15,
             "explanation": "Like the wooden horse of Troy, trojans disguise themselves as useful software to get past your defences, then cause harm from inside.",
             "hint": "It looks harmless but carries a hidden threat inside."},
            {"body": "What does antivirus software do?",
             "a": "Makes your internet faster",
             "b": "Detects, quarantines, and removes malicious software from your device",
             "c": "Blocks all websites",
             "d": "Backs up your files",
             "correct": "b", "points": 15,
             "explanation": "Antivirus software scans your device for known malware patterns, quarantines threats, and removes them.",
             "hint": "It's a guard that looks for and removes threats."},
            {"body": "Why are free 'cracked' versions of paid software dangerous?",
             "a": "They are slower than the paid version",
             "b": "They often contain hidden malware and bypass security checks",
             "c": "They use too much storage space",
             "d": "They are only dangerous on older computers",
             "correct": "b", "points": 15,
             "explanation": "Cracked software skips security verification and distributors frequently bundle malware with it. You risk your device and data for 'free' software.",
             "hint": "There's rarely a truly free lunch in software piracy."},
            {"body": "What is a 'drive-by download'?",
             "a": "Downloading an app from your car",
             "b": "Malware that automatically downloads when you visit a compromised website, without you clicking anything",
             "c": "A fast download method",
             "d": "Downloading in the background while gaming",
             "correct": "b", "points": 15,
             "explanation": "Drive-by downloads exploit browser vulnerabilities to install malware automatically when visiting a compromised or malicious website.",
             "hint": "No click required — just visiting a bad site is enough."},
        ],
        "advanced": [
            {"body": "What is a 'zero-day vulnerability'?",
             "a": "A bug that only exists for one day",
             "b": "A newly discovered security flaw with no available patch yet",
             "c": "A vulnerability in day-zero software releases",
             "d": "A type of phishing attack",
             "correct": "b", "points": 20,
             "explanation": "Zero-day vulnerabilities are unknown to the software vendor, giving them zero days to patch it. Attackers can exploit them before any fix is available.",
             "hint": "Zero days for developers to fix it before exploitation."},
            {"body": "What is 'code signing' and why does it matter for downloads?",
             "a": "Adding your name to code as a copyright",
             "b": "A cryptographic method where publishers digitally sign software to verify its authenticity and integrity",
             "c": "A technique to make code run faster",
             "d": "A law requiring software documentation",
             "correct": "b", "points": 20,
             "explanation": "Code signing uses cryptographic signatures to prove software came from the claimed publisher and hasn't been tampered with after release.",
             "hint": "A digital seal of authenticity."},
            {"body": "What is a 'supply chain attack' in the context of software?",
             "a": "Attacking a company's physical supply chain",
             "b": "Compromising legitimate software or its update mechanism to distribute malware to end users",
             "c": "Stealing software source code",
             "d": "Blocking software downloads for competitors",
             "correct": "b", "points": 20,
             "explanation": "Supply chain attacks inject malicious code into trusted software during development or distribution — victims unknowingly install malware via trusted channels.",
             "hint": "Attack the trusted source, not the end user directly."},
            {"body": "What is 'sandboxing' in the context of software security?",
             "a": "Playing games in a sandbox environment",
             "b": "Running suspicious software in an isolated environment where it cannot affect the main system",
             "c": "Hiding files in encrypted containers",
             "d": "Testing software on a separate server",
             "correct": "b", "points": 20,
             "explanation": "A sandbox is an isolated execution environment. Suspicious code runs there so that if it's malicious, it cannot escape to harm the real system.",
             "hint": "Like a real sandbox — it contains what's inside."},
            {"body": "What is the principle of 'least privilege' for software permissions?",
             "a": "Giving apps the maximum permissions for better performance",
             "b": "Granting only the minimum permissions necessary for software to perform its function",
             "c": "Allowing only admin accounts to install software",
             "d": "Restricting all apps from network access",
             "correct": "b", "points": 20,
             "explanation": "Least privilege minimises damage if software is compromised. An app with minimal permissions can do less damage if it turns malicious.",
             "hint": "Only what's needed — nothing more."},
        ],
    },

    # ══════════════════════════════════════════════════════
    # DEVICE SECURITY
    # ══════════════════════════════════════════════════════
    "device_security": {
        "beginner": [
            {"body": "Why should you lock your phone with a PIN or password?",
             "a": "To make it look cool",
             "b": "To stop others from accessing your personal information if your phone is lost or stolen",
             "c": "It makes the battery last longer",
             "d": "It is required by law",
             "correct": "b", "points": 10,
             "explanation": "A screen lock is your first line of defence. Without it, anyone who picks up your phone can access everything on it.",
             "hint": "Think about what happens if you lose your unlocked phone."},
            {"body": "What should you do if you lose your phone?",
             "a": "Buy a new one immediately",
             "b": "Use a 'Find My Device' feature to locate it and remotely wipe it if necessary",
             "c": "Do nothing — someone will return it",
             "d": "Call the police immediately",
             "correct": "b", "points": 10,
             "explanation": "Remote locate and wipe features (like Find My iPhone or Android's Find My Device) let you protect your data even after losing the device.",
             "hint": "Most phones have a built-in feature to find and wipe them remotely."},
            {"body": "Is it safe to charge your phone at a public USB charging station?",
             "a": "Yes, completely safe",
             "b": "Only if the station looks clean",
             "c": "No — public USB ports can be used for 'juice jacking' to steal data or install malware",
             "d": "Only when travelling abroad",
             "correct": "c", "points": 10,
             "explanation": "Juice jacking exploits USB ports to steal data or install malware. Use your own charger with a wall outlet or use a charge-only USB data blocker.",
             "hint": "USB cables can transfer data, not just power."},
            {"body": "What does it mean to 'factory reset' a device?",
             "a": "Returning it to the shop",
             "b": "Updating all apps to the latest version",
             "c": "Wiping all data and returning the device to its original settings",
             "d": "Fixing a broken screen",
             "correct": "c", "points": 10,
             "explanation": "A factory reset erases everything on a device. Always do this before giving away, selling, or disposing of an old device.",
             "hint": "It wipes the slate completely clean."},
            {"body": "Your friend wants to borrow your device for 'just a moment'. What should you do?",
             "a": "Hand it over without worry",
             "b": "Stay with them while they use it and ensure they don't access private areas",
             "c": "Give them your PIN so they can use it alone",
             "d": "Let them install any apps they want",
             "correct": "b", "points": 10,
             "explanation": "Even trusted friends should have limited, supervised access to your device. Your private data deserves protection.",
             "hint": "Your data is still private even from friends."},
        ],
        "intermediate": [
            {"body": "What is 'two-factor authentication' (2FA) and why is it important for device security?",
             "a": "Using two different devices simultaneously",
             "b": "A second verification step that protects accounts even if the password is compromised",
             "c": "A feature that doubles internet speed",
             "d": "Logging in twice for confirmation",
             "correct": "b", "points": 15,
             "explanation": "2FA requires a second proof of identity (like a code from your phone), making it much harder for attackers to access accounts even with your password.",
             "hint": "Two locks are better than one."},
            {"body": "What is Bluetooth security risk 'bluejacking'?",
             "a": "Stealing a Bluetooth speaker",
             "b": "Sending unsolicited messages to nearby Bluetooth devices",
             "c": "Hacking via the colour blue",
             "d": "A way to boost Bluetooth range",
             "correct": "b", "points": 15,
             "explanation": "Bluejacking sends anonymous messages to nearby Bluetooth devices. While often harmless, it can be used for spam or harassment.",
             "hint": "Unsolicited messages via Bluetooth to nearby devices."},
            {"body": "Why should you turn off WiFi when not using it?",
             "a": "It saves electricity only",
             "b": "Leaving WiFi on allows your device to automatically connect to known or fake networks",
             "c": "It makes your phone faster",
             "d": "WiFi affects GPS accuracy",
             "correct": "b", "points": 15,
             "explanation": "Your device remembers network names and may auto-connect to a fake network set up with a common name. Turning off WiFi prevents this.",
             "hint": "Auto-connect features can be exploited."},
            {"body": "What is 'screen time' management and why does it matter for security?",
             "a": "Only important for children's health",
             "b": "Also a security tool — it limits access to apps and prevents unauthorised purchases or downloads",
             "c": "Only affects app notifications",
             "d": "It is purely a battery saving feature",
             "correct": "b", "points": 15,
             "explanation": "Screen time controls can block specific apps, prevent app installations without a passcode, and limit in-app purchases — all security benefits.",
             "hint": "It can also prevent unwanted app installs and purchases."},
            {"body": "What is a firewall and what does it do for device security?",
             "a": "A physical barrier protecting the device from fire",
             "b": "Software or hardware that monitors and controls network traffic based on security rules",
             "c": "A backup system for data",
             "d": "An antivirus scan tool",
             "correct": "b", "points": 15,
             "explanation": "A firewall acts as a gatekeeper — it examines incoming and outgoing network traffic and blocks connections that violate security rules.",
             "hint": "A guard that decides what traffic can pass."},
        ],
        "advanced": [
            {"body": "What is 'rooting' or 'jailbreaking' a device and what are the risks?",
             "a": "Restarting a device in recovery mode — completely safe",
             "b": "Removing manufacturer restrictions to gain full OS access — but it removes security protections too",
             "c": "A technique to improve battery life safely",
             "d": "A factory reset by a different name",
             "correct": "b", "points": 20,
             "explanation": "Rooting/jailbreaking gives you deeper control but bypasses security sandboxes, voids warranties, and exposes the device to greater malware risk.",
             "hint": "More control = fewer built-in protections."},
            {"body": "What is a 'man-in-the-middle' (MitM) attack on a device?",
             "a": "A person physically standing between two computers",
             "b": "An attacker secretly intercepting and potentially altering communication between two parties",
             "c": "A type of social engineering attack",
             "d": "A virus that deletes files midway through saving",
             "correct": "b", "points": 20,
             "explanation": "In a MitM attack, the attacker positions themselves between the victim and the server, secretly reading or altering communications.",
             "hint": "The attacker is secretly in the middle of your communication."},
            {"body": "What does full-disk encryption protect against?",
             "a": "Virus infections", "b": "Slow performance",
             "c": "Unauthorised access to data if the device is lost or stolen",
             "d": "Remote hacking attacks",
             "correct": "c", "points": 20,
             "explanation": "Full-disk encryption scrambles all data on the device. Without the correct password/key, a thief can't read any data even with physical access.",
             "hint": "It protects physical possession of the device."},
            {"body": "What is a 'hardware security key' (like YubiKey) used for?",
             "a": "Unlocking physical doors with your phone",
             "b": "A physical device providing unphishable 2FA that requires physical presence to authenticate",
             "c": "Encrypting files on your hard drive",
             "d": "Boosting WiFi signal",
             "correct": "b", "points": 20,
             "explanation": "Hardware security keys provide cryptographic proof of physical possession. Unlike SMS codes, they cannot be intercepted by phishing attacks.",
             "hint": "Physical, phishing-resistant second factor."},
            {"body": "What is 'mobile device management' (MDM) used for in organisations?",
             "a": "Managing phone call records",
             "b": "Centrally managing, monitoring, and securing mobile devices within an organisation",
             "c": "Reducing employees' screen time",
             "d": "Tracking employees' location at all times",
             "correct": "b", "points": 20,
             "explanation": "MDM lets IT departments remotely configure, monitor, update, and wipe organisation-owned or registered devices to enforce security policies.",
             "hint": "Central control of an organisation's fleet of devices."},
        ],
    },
}

# ─── Seed into DB ────────────────────────────────────────────────────────────

def run() -> None:
    added = 0
    skipped = 0

    with get_db() as db:
        # Build a map: (topic, age_group, difficulty) → module_id
        modules = db.query(Module).all()
        mod_map: dict[tuple, int] = {}
        for m in modules:
            db.expunge(m)
            key = (m.topic, m.age_group, m.difficulty)
            mod_map[key] = m.id

    print(f"Found {len(mod_map)} modules in database.")

    age_groups = ["junior", "explorer", "ranger"]

    for topic, diff_bank in QUESTIONS.items():
        for difficulty, q_list in diff_bank.items():
            for age_group in age_groups:
                key = (topic, age_group, difficulty)
                module_id = mod_map.get(key)
                if module_id is None:
                    print(f"  SKIP: No module for {key}")
                    continue

                with get_db() as db:
                    for q in q_list:
                        existing = db.query(Question).filter_by(
                            module_id=module_id, body=q["body"]
                        ).first()
                        if existing:
                            skipped += 1
                            continue

                        new_q = Question(
                            module_id=module_id,
                            body=q["body"],
                            option_a=q["a"],
                            option_b=q["b"],
                            option_c=q["c"],
                            option_d=q["d"],
                            correct_option=q["correct"],
                            explanation=q["explanation"],
                            difficulty=difficulty,
                            hint=q.get("hint", ""),
                            points=q.get("points", 10),
                            is_active=True,
                        )
                        db.add(new_q)
                        added += 1

    print(f"\nDone! Added {added} new questions, skipped {skipped} existing.")


if __name__ == "__main__":
    run()
